title: Dashboard Frontend - Gaiadex
email: guilyra12@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Data analysis provided by SonarCloud.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://fga-eps-mds.github.io/2020.1-GaiaDex-FrontEnd/" # the base hostname & protocol for your site, e.g. http://example.com
show_downloads: true
markdown: kramdown
theme: jekyll-theme-midnight

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
