name: Homolog Continuous Delivery

on:
  pull_request:
    branches: 
      - develop
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Modules
        run: npm ci
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_REPORTER_ID}}
        with:
          coverageCommand: npm run test
  build:
    name: CI Build
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: |
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          npm ci
          cd ./android
          ./gradlew assembleRelease
      - uses: actions/upload-artifact@master
        with:
          name: apk
          path: ./android/app/build/outputs/apk/release/

  tagged-release:
    name: "Tagged Release"
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Downlaod APK File
        uses: actions/download-artifact@master
        with:
          name: apk
          path: ~/apk/
      - name: log
        run: ls ~/apk/
      - name: Add Github Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "homolog"
          prerelease: true
          files: |
            LICENSE.txt
            *.apk